# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/diffusion',
                'doc_host': 'https://seeM.github.io',
                'git_url': 'https://github.com/seeM/diffusion',
                'lib_path': 'diffusion'},
  'syms': {'diffusion.core': {'diffusion.core.foo': ('core.html#foo', 'diffusion/core.py')}}}